inimal_mistakes_skin    : "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR" 
title                    : "Programming Guide"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "TALOS"
description              : "" 
url                      : "https://talos-25309.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "https://github.com/TALOS-25309/Programming-Guidebook"             # Github repo url
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
theme: jekyll-theme-cayman
